# Prefix
bind 'C-a' send-prefix

# Mouse
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys -M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down

# Copy Mode
setw -g mode-keys vi
unbind -T copy-mode-vi Enter
bind-key -T copy-mode-vi Enter send-keys -X cancel
unbind -T copy-mode-vi MouseDragEnd1Pane
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe "xclip -i -selection clipboard && xclip -i -selection primary" \; copy-mode -e
bind -T copy-mode-vi C-Left send-keys -X previous-word
bind -T copy-mode-vi C-Right send-keys -X next-word

# Navigation
bind -n S-Left previous-window
bind -n S-Right next-window

# Custom
bind j attach -c "#{pane_current_path}"
bind J attach -c "#{pane_current_path}" \; run-shell "tmux list-panes -F '##{pane_id}' | grep -v $(tmux display-message -p '##{pane_id}') | xargs -I{} tmux send-keys -t {} 'cd #{pane_current_path}' Enter"
bind C send-keys "copyq eval 'add(clipboard())'"
bind g send-keys "&> /dev/null & disown"
bind U split-window "aliasr send -pp"
bind K split-window "aliasr -e send -pp"
