# Server
set -s escape-time 0
set -s focus-events on
set -s default-terminal "tmux-256color"
set -as terminal-overrides ",*:Tc"

# General
set -g prefix 'C-a'
unbind 'C-b'
set -g history-limit 10000
set -g allow-rename off
setw -g automatic-rename off
set -g xterm-keys on
set -g base-index 1
setw -g pane-base-index 1
set-option -g renumber-windows on

# Display
set -g status-interval 10
set -g display-panes-time 800
set -g display-time 1000
set-option -g clock-mode-style 12

# Mouse
set -g mouse on
