# Setup
tmux_dir="~/.config/tmux"
tmux_conf_dir="$tmux_dir/config"
tmux_plugins_dir="$tmux_dir/plugins"

# Configuration
source "$tmux_conf_dir/options.conf"
source "$tmux_conf_dir/keybindings.conf"
source "$tmux_conf_dir/theme.conf"

# Plugins
set-environment -g TMUX_PLUGIN_MANAGER_PATH "$tmux_plugins_dir"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'MunifTanjim/tmux-mode-indicator'

run '~/.config/tmux/plugins/tpm/tpm'
run '~/.config/tmux/plugins/tmux-mode-indicator/mode_indicator.tmux'
